version: '3'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    image: postgres:10.1-alpine
    restart: always
    env_file: ./.env
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups

  django:
    image: jambonrose/django-20-simplelist-training:4821e4853c2046
    depends_on:
      - postgres
    env_file: ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
